services:
  db:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: flakeguard
    ports:
      - "5432:5432"
    volumes:
      - fg_db:/var/lib/postgresql/data

  app:
    build: .
    environment:
      FG_ENV: dev
      FG_HTTP_ADDR: :8080
      FG_BASE_URL: http://localhost:8080
      FG_DB_DSN: postgres://postgres:postgres@db:5432/flakeguard?sslmode=disable
      FG_JWT_SECRET: change-me-in-dev-please-change
      FG_LOG_LEVEL: debug
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  fg_db: {}
